### PR TITLE
Run LLVM sanitizers on GitHub Actions

### PR DESCRIPTION
**Pull request by jviotti**
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
Signed-off-by: Tony Gorez <gorez.tony@gmail.com>

### CODE REVIEW

**Comment by tony-go** [comment]
I'm trying to reproduce locally.

**Comment by tony-go** [comment]
I finally reproduce it on Fedora ARM :)

**Comment by jviotti** [comment]
Awesome! Looking forward to the fix

**Comment by tony-go** [comment]
2 leaks caught 🔥

**Pull request merged**
